# container-based build
sudo: false

language: scala

# These directories are cached to S3 at the end of the build
cache:
  directories:
   - $HOME/.m2
   - $HOME/.ivy2
   - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

scala:
  - 2.11.8

jdk:
  - oraclejdk8

script:
  - git config --local user.email "scf370@gmail.com"
  - git config --local user.name "Travis"
  - export RELEASE_VERSION=$(sed 's/[^0-9]//g' version.sbt)
  - sbt dist
  - tar -C target/dist -cvjf dist.tar.bz2 .
  - curl -T dist.tar.bz2 -uscf37:$(cat .secret-enc/bintray_key | openssl aes-256-cbc -a -d -k "$PASSWORD") https://api.bintray.com/content/scf37/generic/mongoschema/$RELEASE_VERSION/mongoschema-$RELEASE_VERSION.tar.bz2'?publish=1'
  - curl -T dist.tar.bz2 -uscf37:$(cat .secret-enc/bintray_key | openssl aes-256-cbc -a -d -k "$PASSWORD") https://api.bintray.com/content/scf37/generic/mongoschema/latest/mongoschema-latest.tar.bz2'?publish=1&override=1'
  - eval "$(ssh-agent -s)" #start the ssh agent
  - cat .secret-enc/github_key | openssl aes-256-cbc -a -d -k "$PASSWORD" > github_key
  - chmod 600 github_key
  - ssh-add github_key
  - git remote add deploy git@github.com:scf37/mongoschema.git
  - git branch -f master HEAD
  - git checkout master
  - git status
  - git push deploy master
